export const spotifyConstants = {
  FETCH_CATEGORIES_REQUEST: "FETCH_CATEGORIES_REQUEST",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",

  FETCH_PLAYLIST_REQUEST: "FETCH_PLAYLIST_REQUEST",
  FETCH_PLAYLIST_SUCCESS: "FETCH_PLAYLIST_SUCCESS",
  FETCH_PLAYLIST_FAILURE: "FETCH_PLAYLIST_FAILURE",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
